name: glicogotas_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.0

  

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10
  audioplayers: ^6.1.0
  shared_preferences: ^2.3.3
  just_audio: ^0.9.42
  sqflite: ^2.4.1
  path: ^1.9.0
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1


flutter_icons:
  ios: true
  android: true
  image_path: "assets/icon/icon.png"
  


  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/glicogotas_logo.png
    - assets/images/talita_icon.png
    - assets/images/diabetes-capa.png
    - assets/images/chaves-capa.png
    - assets/images/insulina-capa.png
    - assets/images/pancreas-capa.png
    - assets/images/tirinha-docura-capa.png
    - assets/images/tirinha-insu-capa.png
    - assets/images/tirinha-ins-1.png
    - assets/images/tirinha-ins-2.png
    - assets/images/tirinha-ins-3.png
    - assets/images/talita_capa.png
    - assets/images/tirinha1.png
    - assets/images/tirinha2.png
    - assets/images/tirinha3.png
    - assets/images/decoracao.svg
    - assets/images/person.svg
    - assets/images/livro.svg
    - assets/images/historia.svg
    - assets/images/jogos.svg
    - assets/images/tela-inicial-perso.svg
    - assets/images/fundo-azul.svg
    - assets/images/btn-avancar-branco.svg
    - assets/images/fundo-lita.svg
    - assets/images/btn-avancar-azul.svg
    - assets/images/lita-person.svg
    - assets/images/lita-heroina.svg
    - assets/images/fundo-rei.svg
    - assets/images/rei-da-hiper.svg
    - assets/images/eclipse-rei.svg
    - assets/images/fundo-bobo.svg
    - assets/images/eclipse-bobo.svg
    - assets/images/bobo-person.svg
    - assets/images/fundo-fe.svg
    - assets/images/eclipse-fe.svg
    - assets/images/fe-person.svg
    - assets/images/fundo-insulins.svg
    - assets/images/eclipse-insulins.svg
    - assets/images/insulins-person.svg
    - assets/images/pumps-person.svg
    - assets/images/eclipse-pumps.svg
    - assets/images/fundo-pumps.svg
    - assets/images/fundo-betinho.svg
    - assets/images/eclipse-betinho.svg
    - assets/images/betinho-person.svg
    - assets/images/fundopaglivro.svg
    - assets/images/btn-avancar-laranja.svg
    - assets/images/lita.svg    
    - assets/images/balão-duplo.svg
    - assets/images/btn-voltar-laranja.svg
    - assets/images/balão-page2.svg
    - assets/images/lita-falando.svg
    - assets/images/balão-page3.svg
    - assets/images/fundo-hist.svg
    - assets/images/lita-pancreas.svg
    - assets/images/balão-page4.svg  
    - assets/images/balão-page5.svg    
    - assets/images/balão-page6.svg
    - assets/images/balão-page7.svg
    - assets/images/pancreas.svg
    - assets/images/error.svg
    - assets/audio/titulo.mp3
    - assets/audio/panc-pagina1.mp3
    - assets/audio/musica.mp3
    - assets/audio/panc-pagina2.mp3
    - assets/audio/panc-pagina3.mp3
    - assets/audio/panc-pagina4.mp3
    - assets/audio/panc-pagina5.mp3
    - assets/audio/panc-pagina6.mp3
    - assets/audio/panc-pagina7.mp3
    - assets/audio/audioPersonagens/bemvindos.mp3
    - assets/audio/audioPersonagens/betinho.mp3
    - assets/audio/audioPersonagens/bobo.mp3
    - assets/audio/audioPersonagens/fe.mp3
    - assets/audio/audioPersonagens/hiper.mp3
    - assets/audio/audioPersonagens/insulins.mp3
    - assets/audio/audioPersonagens/lita.mp3
    - assets/audio/audioPersonagens/pumps.mp3


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package



