// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIoCAltFJ7NJKgTB01o5_dUuU8M0rBR2Y',
    appId: '1:784189351464:web:f0fd209472bba1ed00b71d',
    messagingSenderId: '784189351464',
    projectId: 'glicogotas-app',
    authDomain: 'glicogotas-app.firebaseapp.com',
    storageBucket: 'glicogotas-app.firebasestorage.app',
    measurementId: 'G-LF22H0240M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp2MYaR3VnOM-Rl6_ddUbIaTmIgotV7vY',
    appId: '1:784189351464:android:4bba82c5740cf6d800b71d',
    messagingSenderId: '784189351464',
    projectId: 'glicogotas-app',
    storageBucket: 'glicogotas-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9mp2F1O2jpBtX1k2q_0892RlRfTLLshA',
    appId: '1:784189351464:ios:4666defdb63af48e00b71d',
    messagingSenderId: '784189351464',
    projectId: 'glicogotas-app',
    storageBucket: 'glicogotas-app.firebasestorage.app',
    iosBundleId: 'com.example.glicogotasApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9mp2F1O2jpBtX1k2q_0892RlRfTLLshA',
    appId: '1:784189351464:ios:4666defdb63af48e00b71d',
    messagingSenderId: '784189351464',
    projectId: 'glicogotas-app',
    storageBucket: 'glicogotas-app.firebasestorage.app',
    iosBundleId: 'com.example.glicogotasApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIoCAltFJ7NJKgTB01o5_dUuU8M0rBR2Y',
    appId: '1:784189351464:web:215d82d2266553e500b71d',
    messagingSenderId: '784189351464',
    projectId: 'glicogotas-app',
    authDomain: 'glicogotas-app.firebaseapp.com',
    storageBucket: 'glicogotas-app.firebasestorage.app',
    measurementId: 'G-1LEXX9ZMB6',
  );
}
